#ifndef _SYSCNTRL_INTERFACE_H
#define _SYSCNTRL_INTERFACE_H

void SYSCNTRL_vidEnableSleep(u8 u8Mode);


#define SYSCNTRL_SLEEPMODE_IDLE 0
#define SYSCNTRL_SLEEPMODE_PWDOWN 1
#define SYSCNTRL_SLEEPMODE_PWSAVE 2
#define SYSCNTRL_SLEEPMODE_STANDBY 3
#define SYSCNTRL_SLEEPMODE_ESTANDBY 4

#define SE 7
#define SM0 4
#define SM1 5
#define SM2 6

#endif
