#!/usr/bin/env bash

#Shell script to install various packages needed for
#embedded software development on AVR microcontrollers
#Script started on 22 March 2020

#Check if script is run by root
if [ "$(whoami)" != "root" ]
then
	echo "Need to run as root!"
	echo "Use: sudo $0"
else
#To get the latest packages list
	apt-get update
	apt-get install vim
	apt-get install git
	apt-get install curl
	apt-get install avrdude
	apt-get install gcc-avr
	apt-get install doxygen
	apt-get install graphviz
	apt-get install universal-ctags
	apt-get install dos2unix
	apt-get intall unix2dos
fi
