#!/usr/bin/env bash

#Shell script to install various packages needed for
#embedded software development on AVR microcontrollers
#Script started on 22 March 2020


setupVim ()
{
#install plugin manager
	echo "Setting vim up..."
	rm -r /home/mohamed/.vim/bundle/*
	git clone https://github.com/VundleVim/Vundle.vim.git /home/mohamed/.vim/bundle/Vundle.vim
	#Copying vimrc to home directory
	echo "Copying .vimrc"
	cd /home/mohamed/programming/AVR-ATMega32-drivers-and-tools/tooling/
	cp .vimrc /home/mohamed/
}

#Check if script is run by root
if [ "$(whoami)" != "root" ]
then
	echo "Need to run as root!"
	echo "Use: sudo $0"
else
#To get the latest packages list
	apt-get update
	apt-get install vim
	apt-get install git
	apt-get install curl
	apt-get install avrdude
	apt-get install gcc-avr
	apt-get install avr-libc
	apt-get install doxygen
	apt-get install graphviz
	apt-get install universal-ctags
	apt-get install dos2unix
	apt-get install python3-pip
	apt-get install python3-tk 
	#Setup vim (installing plugin manager)
	setupVim
fi

createProgramming()
{
#Move to home
cd
#Execute command and silence the error
if mkdir programming &> /dev/null
then
	echo "Created directory: programming"
	cd ./programming
	git clone https://github.com/Mohammed-AhmedAF/IMT-course	
	cp ./IMT-course/tooling/get-avr /usr/bin
else
	echo "Error creating directory: programming"
fi
}
