#!/usr/bin/env bash

# Developer: Mohamed Ahmed
# Date: 29 March 2018

AVR_LIB_PATH=$HOME/programming/imt/lib

if [[ $# -eq 0 ]]
then
	cp $AVR_LIB_PATH/* ./
	echo "Copied all files"
else
	for i in $@
	do
		if [[ $i = "makef" ]]
		then
			cp $AVR_LIB_PATH/Makefile ./
		elif [[ $i = "std" ]]
		then
			cp $AVR_LIB_PATH/Std_Types.h ./
		elif [[ $i = "macors" ]]
		then 
			cp $AVR_LIB_PATH/Macros.h ./
		elif [[ $i = "dio" ]]
		then
 			cp $AVR_LIB_PATH/DIO_prog.c ./
 			cp $AVR_LIB_PATH/DIO_interface.h ./
 			cp $AVR_LIB_PATH/Std_Types.h ./
 			cp $AVR_LIB_PATH/Macros.h ./
		elif [[ $i = "lcd" ]]
		then
			cp $AVR_LIB_PATH/LCD_prog.c ./
			cp $AVR_LIB_PATH/LCD_interface.h ./
		elif [[ $i = "key" || $i = "keypad" ]]
		then
			cp $AVR_LIB_PATH/KEYPAD_prog.c ./
			cp $AVR_LIB_PATH/KEYPAD_interface.h ./
			cp $AVR_LIB_PATH/SERVICES_prog.c  ./
			cp $AVR_LIB_PATH/SERVICES_interface.h ./
		elif [[ $i = "eeprom" ]]
		then 
			cp $AVR_LIB_PATH/EEPROM_prog.c ./
			cp $AVR_LIB_PATH/EEPROM_interface.h ./
		elif [[ $i = "rto" ]]
		then
			cp $AVR_LIB_PATH/RTO_prog.c ./
			cp $AVR_LIB_PATH/RTO_interface.h ./
		elif [[ $i = "twi" ]]
		then
			cp $AVR_LIB_PATH/TWI_prog.c ./
			cp $AVR_LIB_PATH/TWI_interface.h ./
		elif [[ $i = "uart" ]]
		then
			cp $AVR_LIB_PATH/UART_prog.c ./
			cp $AVR_LIB_PATH/UART_interface.h ./
		elif [[ $i = "7s" ]]
		then
			cp $AVR_LIB_PATH/SevenSegment_prog.c ./
			cp $AVR_LIB_PATH/SevenSegment_interface.h ./
		elif [[ $i = "stepper" ]]
		then
			cp $AVR_LIB_PATH/StepperMotor_prog.c ./
			cp $AVR_LIB_PATH/StepperMotor_interface.h ./
		elif [[ $i = "timer0" ]]
		then
			cp $AVR_LIB_PATH/TIMER0_prog.c ./
			cp $AVR_LIB_PATH/TIMER0_interface.h ./
		elif [[ $i = "timer1" ]] 
		then 
			cp $AVR_LIB_PATH/TIMER1_prog.c ./
			cp $AVR_LIB_PATH/TIMER1_interface.h ./
		elif [[ $i = "timer2" ]]
		then
			cp $AVR_LIB_PATH/TIMER2_prog.c ./
			cp $AVR_LIB_PATH/TIMER2_interface.h ./
		elif [[ $i = "interrupts" || $i = "INTERRUPTS" || $i = "interrupt" ]]
		then
			cp $AVR_LIB_PATH/INTERRUPTS_prog.c ./
			cp $AVR_LIB_PATH/INTERRUPTS_interface.h ./
		elif [[ $i = "adc" || $i = "ADC" ]]
		then
			cp $AVR_LIB_PATH/ADC_prog.c ./
			cp $AVR_LIB_PATH/ADC_interface.h ./
		elif [[ $i = "spi" || $i = "SPI" ]]
		then
			cp $AVR_LIB_PATH/SPI_prog.c ./
			cp $AVR_LIB_PATH/SPI_interface.h ./
		elif [[ $i = "services" || $i = "SERVICES" ]]
		then
			cp $AVR_LIB_PATH/SERVICES_prog.c ./
			cp $AVR_LIB_PATH/SERVICES_interface.h ./
		else
			echo "Error: Could not process $i."
		fi

	done
fi
