#!/usr/bin/env bash

# Developer: Mohamed Ahmed
# Date: 18 February 2018
# Purpose: This is a script that delivers modules
# on demand to the working directory

AVR_LIB_PATH=$HOME/programming/avr-lib/lib

while getopts 'h' OPTIONS; do
	case $OPTIONS in
		-h)
			echo "get-avr tool is used to bring module files to the current working directory."
			echo "Usage: get-avr <Name_of_Module>"
			echo "Example: get-avr spi"
		;;
	esac
done


if [[ $# -eq 0 ]]
then
	cp $AVR_LIB_PATH/* ./
	echo "Copied all files"
else
	for i in $@
	do
		if [[ $i = "makef" || $i = "makefile" || $i = "Makefile" ]]
		then
			cp $AVR_LIB_PATH/Makefile ./
		elif [[ $i = "std" || $i = "Std" ]]
		then
			cp $AVR_LIB_PATH/Std_Types.h ./
		elif [[ $i = "macros" || $i = "Macros" ]]
		then 
			cp $AVR_LIB_PATH/Macros.h ./
		elif [[ $i = "dio" || $i = "DIO " ]]
		then
 			cp $AVR_LIB_PATH/DIO_program.c ./
 			cp $AVR_LIB_PATH/DIO_interface.h ./
			cp $AVR_LIB_PATH/DIO_private.h ./
 			cp $AVR_LIB_PATH/Std_Types.h ./
 			cp $AVR_LIB_PATH/Macros.h ./
		elif [[ $i = "lcd" ||  $i = "LCD" ]]
		then
			cp $AVR_LIB_PATH/LCD_program.c ./
			cp $AVR_LIB_PATH/LCD_interface.h ./
		elif [[ $i = "key" || $i = "keypad" ]]
		then
			cp $AVR_LIB_PATH/KEYPAD_program.c ./
			cp $AVR_LIB_PATH/KEYPAD_interface.h ./
			cp $AVR_LIB_PATH/SERVICES_program.c  ./
			cp $AVR_LIB_PATH/SERVICES_interface.h ./
		elif [[ $i = "eeprom" || $i = "EEPROM" ]]
		then 
			cp $AVR_LIB_PATH/EEPROM_prog.c ./
			cp $AVR_LIB_PATH/EEPROM_interface.h ./
		elif [[ $i = "internal-eeprom" || $i = "InternalEEPROM" ]]
		then
			cp $AVR_LIB_PATH/EEPROM_INTERNAL_program.c ./
			cp $AVR_LIB_PATH/EEPROM_INTERNAL_interface.h ./
			cp $AVR_LIB_PATH/EEPROM_INTERNAL_private.h ./
		elif [[ $i = "rto" ]]
		then
			cp $AVR_LIB_PATH/RTO_prog.c ./
			cp $AVR_LIB_PATH/RTO_interface.h ./
		elif [[ $i = "twi" || $i = "TWI" ]]
		then
			cp $AVR_LIB_PATH/TWI_program.c ./
			cp $AVR_LIB_PATH/TWI_interface.h ./
		elif [[ $i = "uart" || $i = "UART" ]]
		then
			cp $AVR_LIB_PATH/UART_program.c ./
			cp $AVR_LIB_PATH/UART_interface.h ./
		elif [[ $i = "7s" ]]
		then
			cp $AVR_LIB_PATH/SevenSegment_prog.c ./
			cp $AVR_LIB_PATH/SevenSegment_interface.h ./
		elif [[ $i = "stepper" ]]
		then
			cp $AVR_LIB_PATH/StepperMotor_prog.c ./
			cp $AVR_LIB_PATH/StepperMotor_interface.h ./
		elif [[ $i = "timer0" || $i = "TIMER0" ]]
		then
			cp $AVR_LIB_PATH/TIMER0_program.c ./
			cp $AVR_LIB_PATH/TIMER0_interface.h ./
			cp $AVR_LIB_PATH/TIMER0_private.h ./
		elif [[ $i = "timer1" || $i = "TIMER1" ]] 
		then 
			cp $AVR_LIB_PATH/TIMER1_program.c ./
			cp $AVR_LIB_PATH/TIMER1_interface.h ./
			cp $AVR_LIB_PATH/TIMER1_private.h ./
		elif [[ $i = "timer2" || $i = "TIMER2" ]]
		then
			cp $AVR_LIB_PATH/TIMER2_program.c ./
			cp $AVR_LIB_PATH/TIMER2_interface.h ./
		elif [[ $i = "interrupts" || $i = "INTERRUPTS" || $i = "interrupt" ]]
		then
			cp $AVR_LIB_PATH/INTERRUPTS_program.c ./
			cp $AVR_LIB_PATH/INTERRUPTS_interface.h ./
		elif [[ $i = "adc" || $i = "ADC" ]]
		then
			cp $AVR_LIB_PATH/ADC_program.c ./
			cp $AVR_LIB_PATH/ADC_interface.h ./
		elif [[ $i = "spi" || $i = "SPI" ]]
		then
			cp $AVR_LIB_PATH/SPI_program.c ./
			cp $AVR_LIB_PATH/SPI_interface.h ./
			cp $AVR_LIB_PATH/SPI_private.h ./
		elif [[ $i = "services" || $i = "SERVICES" ]]
		then
			cp $AVR_LIB_PATH/SERVICES_program.c ./
			cp $AVR_LIB_PATH/SERVICES_interface.h ./

		else
			echo "Error: Could not process $i."
		fi

	done
fi
