#!/usr/bin/env python3 

##################################################
#Author: Mohammed Ahmed                          #
#Purpose: Analyze hex files generated by avr-gcc #
##################################################



# Record type is stored in bytes 7 : 9
# Actual data in the record is stored from byte 9: -3

fileHandle = open("main.hex","r")

def displayAddresses():
    for i in fileHandle:
        record = fileHandle.readline()
            #If it is a data record
        if record[1:3] == '10':
            #print address contained in record
            print(record[3:7])

def checkExtSegAddressRecord():
    for i in fileHandle:
        record = fileHandle.readline()
        if record[1:3] != '10':
            print(record[1:3])


def displayData():
    for i in fileHandle:
        record = fileHandle.readline()
        if record[1:3] == '10':
            print(record[9:-3])

def printDataRecord():
    for i in fileHandle:
        record = fileHandle.readline()
        if ( record[7:9] == '00'):
            print(record)

def extractTypes():
    types = list()
    for i in fileHandle:
        record = fileHandle.readline()
        if record[7:9] not in types:
            types.append(record[7:9])


    print(types)

printDataRecord()
