#!/usr/bin/env bash

#Putting drivers of an already created project in dedicated directories based on software layer

#Making directories for layers
mkdir APP &> /dev/null
mkdir HAL &> /dev/null
mkdir MCAL &> /dev/null
mkdir UTIL &> /dev/null

#Copy makefile
cp ~/programming/IMT-course/lib/Makefile-layered ./Makefile

#Move to UTIL
mv Std_Types.h ./UTIL &> /dev/null
mv Macros.h ./UTIL &> /dev/null
mv SERVICES* ./UTIL &> /dev/null

#Move to MCAL 
mv DIO* ./MCAL &> /dev/null
mv SPI* ./MCAL &> /dev/null
mv UART* ./MCAL &> /dev/null
mv TWI* ./MCAL &> /dev/null
mv INTERRUPTS* ./MCAL &> /dev/null
mv ADC* ./MCAL &> /dev/null
mv TIMER0* ./MCAL  &> /dev/null
mv TIMER1* ./MCAL &> /dev/null
mv TIMER2* ./MCAL &> /dev/null
mv SETTINGS* ./MCAL &> /dev/null
mv EEPROM_INTERNAL* ./MCAL &> /dev/null

#Move to HAL
mv DHT22* ./HAL &> /dev/null
mv LCD* ./HAL &> /dev/null
mv RTC* ./HAL &> /dev/null
mv EEPROM_EXTERNAL* &> /dev/null
mv KEYPAD* ./HAL &> /dev/null

#Move to APP
mv main.c ./APP &> /dev/null


